### ISSUE TITLE
ListPosts Component: default behavior

### ISSUE THREAD

**Issue by vandebled** [flyntwp/flynt-starter-theme#201]
We should maybe discuss the default behavior that the `ListPost`component should have.
Since the password protection concept is integrated, shouldn't we also hide private posts? Also should the password protected posts show up in the list?
What about the sticky posts?
Should all these concepts be integrated, or do they have to be integrated by project when they are needed?

**Comment by emcarru** [comment]
Personally I expected the `ListPost` component to work with all the possible default options a user can select in the back-end under "Publish". This is:

- Visibility: Public/Private/Password protected
- Sticky posts
- Status: Published / Pending Review / Draft

Either that, or we need a default Feature to disable/enable those options in the back-end. I think otherwise people will forget to test every use-case (we probably already forget to test all of these options sometimes).

**Comment by vandebled** [comment]
Tested a bunch of cases:

Private posts work.
Password protected work apart from breaking the archive pages when the first on the list is password protected.
Sticky posts work.
Pending Review posts work.
Draft posts work.
