### ISSUE TITLE
How to disable the oEmbed for wysiwyg type on Flynt Theme

### ISSUE THREAD

**Issue by forevereffort** [flyntwp/flynt-starter-theme#310]
```
namespace Flynt\Components\ContentSection;

function getACFLayout()
{
    return [
        'name' => 'contentSection',
        'label' => 'Content Section',
        'sub_fields' => [
            [
                'label' => 'Content',
                'name' => 'content',
                'type' => 'wysiwyg',
                'delay' => 1,
                'media_upload' => 0,
                'wrapper' => [
                    'class' => 'autosize',
                ],
            ]
        ]
    ];
}
```

I added my component by the above code.

when I inserted `https://www.facebook.com/ksdktv/videos/10156234412094312`  , that URL is changing to the Facebook video play on Admin Edit Page and FrontPage.

how can I disable this function?

**Comment by domtra** [comment]
hi @forevereffort, this is the default functionality from tinymce in wordpress. there is nothing we implemented additionally to get this behavior. if you want to disable this, check https://kinsta.com/knowledgebase/disable-embeds-wordpress/

also, this is an old repo. i will archive it now, so that there is no confusion anymore, where to ask questions. the new repo is https://github.com/flyntwp/flynt
happy to help you out over there from now on.
